.github/workflows/pull-request.yaml
.sqlfluff

Configures a linter to run on every commit and ensure consistent SQL style

Configure linter

---

cowamm/profitability/10k_growth/daily_rebalancing_4055484.sql

Otherwise the investment of 10k graph looks off:
Before
After

Make daily rebelancing query start at 10k

---

cowamm/profitability/10k_growth/cow_4047078.sql

The TVL was taken directly from [this helper query](https://dune.com/queries/4059700). However its $ value represents the TVL at the time of the last trade (not at the end of each day). This led to CoW AMM not tracking the rebalancing and Uniswap portfolio as closely as it should.
This PR instead uses the raw token balances and joins them with up to date closing prices for each day to get a more correct TVL.
New USDC/WETH comparison:

[CoW AMM] Fix TVL calculation for 10k growth analysis

---

cowamm/profitability/10k_growth/uni_v2_4047194.sql

Assuming an lp token event every 7 days was too optimistic for pools like MKR/ETH:
This PR changes the performance optimisation by adding another fast subquery to identify the last day we need to consider for the join. This should ensure that the query still runs fast for very active AMMs such as ETH/USDC
- MKR/ETH now shows data
- USDC/ETH still runs in ~1 minute

Fix lookback range for uni lp token supply

---

cowprotocol/accounting/rewards/mainnet/service_fee_query_4017925.sql

This PR updates the reduced bonding pools in the service fees query after #58

Update reduced bonding pools in service fees query

---

cowprotocol/accounting/rewards/mainnet/.sqlfluff
cowprotocol/accounting/rewards/mainnet/block_number_interval_from_time_interval_query_3333356.sql
cowprotocol/accounting/rewards/mainnet/mainnet_dashboard_query_2510345.sql
cowprotocol/accounting/rewards/mainnet/vouch_registry_query_1541516.sql

Simple PR to extend the [block range query](https://dune.com/queries/3333356) to multiple chains.

Extend blockrange query to multiple chains

---

cowprotocol/accounting/rewards/mainnet/partner_fees_query_3602560.sql

This PR adapts one more query that was forgotten, as a follow-up to PR #78

Adapt forgotten query from PR 78

---

cowprotocol/accounting/rewards/mainnet/partner_fees_query_3602560.sql

Update partner fee query to include appcode

---

cowprotocol/accounting/rewards/mainnet/partner_fees_query_3602560.sql

This PR fixes the partner fee query, where some line had been accidentally deleted.

Fix partner fee query bug

---

cowprotocol/revenue/monthly_dao_revenue_3700123.sql

Adding Base to the monthly total view (which will automatically reflect the overall totals)
Base individual tables have already been added to the dashboard (reusing the chain agnostic foundational tables of this repo)

[Revenue] Add Base

---

cowamm/.sqlfluff
cowamm/balancer_cow_amms_3959044.sql
cowamm/dashboard/cow_amms_total_volume_3968105.sql
cowamm/dashboard/cow_amms_tvl_evolution_3968374.sql
cowamm/dashboard/pools_w_links_4546258.sql
cowamm/dashboard/volume_evolution_4346160.sql

Uploading queries from the dune CoW AMMs V2 dashboard.
Updating them to include Base CoW AMMs

Base CoW AMMs

---

cowprotocol/accounting/token_imbalances/balance_changes_4021257.sql

This PR only changes comments.
No detailed review required.

[Easy] Fix comment in balance changes query

---

mevblocker/fees/payment_due_4005800.sql

We had to reduce the price for one payment as it used Jan fee and data, now the fee is going to be 40%

[MevBlocker] rollback temp price reduction

---

cowamm/kpi/competitors/cow_amm/tvl_all_cow_amms_4340356.sql

This PR fixes a small error (1-2 indexing turned to 0-1) in the cow amm tvl query
Change already applied -> https://dune.com/queries/4340356

Rename column in cow amm tvl query

---

cowamm/dashboard/new_dashboard/pools_w_links_4849124.sql
cowamm/dashboard/new_dashboard/total_volume_3968105.sql
cowamm/dashboard/new_dashboard/tvl_over_time_4346160.sql
cowamm/dashboard/new_dashboard/volume_over_time_4346160.sql

Using the new materialized view to speed everything up.
https://dune.com/cowprotocol/cow-amms-v2
Change of surplus formula to exact constant function increase.

Cow amm main dashboard

---

cowamm/profitability/lp_prices/uni_style_lp_4420675.sql

Change token from 1 & 2 to 0 & 1 following a previous PR

Change token references  [Easy]

---

cowprotocol/user_segmentation/.sqlfluff
cowprotocol/user_segmentation/user_segmentation_4872780.sql

Adding user segmentation dashboard under VCS. Next iteration would require adding layered transactions, but will put it into next PR

User segmentation

---

mevblocker/fees/payment_due_4005800.sql

Removed temporary fee reduction. We want fee to become 50%, before it was artificially reduced to 40%.

[MEV Blocker] rollback fee reduction

---

cowamm/balancer_cow_amms_per_chain_4814818.sql
cowamm/cow_amm_cow_with_users_surplus_query_4031724.sql
cowamm/profitability/lp_prices/cow_amm_lp_4420687.sql
cowprotocol/accounting/rewards/full_bonding_pools_query_4056263.sql
cowprotocol/accounting/rewards/partner_fees_query_3602560.sql
cowprotocol/revenue/monthly_dao_revenue_3700123.sql
cowprotocol/solver_dashboard/solver_yields_1756400.sql
cowprotocol/user_segmentation/user_segmentation_4872780.sql

Matching the solver-rewards PR:
https://github.com/cowprotocol/solver-rewards/pull/532

Add one more custom percent for partner

---

cowprotocol/solver_dashboard/ranked_active_solvers_1756858.sql

This PR fixes the issues that were not addressed in PR173:
https://github.com/cowprotocol/dune-queries/actions/runs/15017570795/job/42220932482

Fix linting issues of PR173

---

cowamm/dashboard_micro/cow_amms_invariant_vs_benchmarks_4062641.sql
cowamm/dashboard_micro/cow_amms_vs_benchmarks_4059180.sql
cowamm/kpi/competitors/cow_amm/cow_amm_kpi_4340428.sql
cowamm/profitability/10k_growth/daily_rebalancing_4055484.sql
cowamm/profitability/lp_prices/cow_amm_lp_4420687.sql
cowamm/profitability/lp_prices/uni_style_lp_4420675.sql
cowprotocol/accounting/rewards/partner_fees_query_3602560.sql
cowprotocol/revenue/revenue_per_integration_partner_3938636.sql
cowprotocol/solver_dashboard/batch_settlement_info_1373033.sql
cowprotocol/solver_dashboard/internal_monitoring/solver_quote_rewards_3641173.sql

This PR fixes issues with some of the queries in this repository not following linting rules.
The changes were created using the command `sqlfluff fix .` using sqlfluff version 3.4.2.
A follow up PR will add a hook for automatically fixing linting issues.

Fix linting

---

cowprotocol/accounting/slippage/slippage_prices_4064601.sql

Follow-up to this PR->https://github.com/cowprotocol/dune-queries/pull/244
This PR now fixes the sell token prices, which are basically USDT equivalents, so fix should be much easier.

Fix ausdt Dune price
