mevblocker/fees/.sqlfluff
mevblocker/fees/payment_due_4005800.sql

Migrates [this query](https://github.com/cowprotocol/mev-blocker-dune-queries/pull/3/files#diff-c57e0681fa45c19d6b414337c8b0b493f9c12df496bb0c2b458891a8af9da57b) based on the new existing tables, which makes it a very simple select statement.

Payment Due query

---

mevblocker/fees/payment_status_4016152.sql

Last query (basically taken from https://dune.com/queries/3742749) computes the payment status for each builder (given the latest billing).
We might want to change this query in the future to account for multiple bill transactions (e.g. in case of manual adjustment).

Add query for payment status

---

cowprotocol/accounting/rewards/mainnet/service_fee_query_4017925.sql

Trivial PR that lowercases the service fee query and uses snake case throughout for column names (4017925)

Fix capitalization in service fee query (id 4017925)

---

cowprotocol/accounting/rewards/mainnet/service_fee_query_4017925.sql

The recent changes to the CIP-48 query seem to have introduced an error. This is because the `cow_protocol_ethereum.VouchRegister_evt_Vouch` table uses camel case for the `bondingPool` and `CowRewardTarget` columns. This PR reverts those columns in the CIP-48 query to a naming format that is compatible with the table.

Fix CIP-48 query (id 4017925)

---

cowprotocol/coincidence_of_wants/.sqlfluff
cowprotocol/coincidence_of_wants/balance_changes_4021257.sql
cowprotocol/coincidence_of_wants/classified_balance_changes_4021306.sql
cowprotocol/coincidence_of_wants/cow_per_batch_4025739.sql
cowprotocol/coincidence_of_wants/cow_per_token_4021555.sql
cowprotocol/coincidence_of_wants/cow_total_4025865.sql
cowprotocol/coincidence_of_wants/imbalances_4021644.sql
cowprotocol/coincidence_of_wants/token_prices_4031637.sql

This PR adds queries for computing Coincidence of Wants (CoWs) per batch.
The approach to CoWs follows a [master's thesis](https://wwwmatthes.in.tum.de/pages/y9xcjv094zhn/Master-s-Thesis-Vigan-Lladrovci) by Vigan Lladrovci. It is based on aggregated amounts transferred in and out of the settlement contract by users and other sources (AMMs, PMM, ...). This gives a metric for CoWs and for potential for CoWs for batches. The main idea is to aggregate per token bought in a batch the difference of the total usd volume of that token sold and the total volume sent towards AMMs. Aggregated over all tokens in a batch, this quantity can be compared to the total volume.
The original approach had problems taking internalizations into account. and excluded such batches from its analysis. Here, the …

Coincidence of Wants query

---

cowprotocol/coincidence_of_wants/cow_per_batch_4025739.sql

This PR removes symmetriced cow vaules from the bcow per batch query.
In a refactoring, this value was removed in all queries except for this one.
I am not sure how to checkf whether the query work fine if not for copying changes manually to Dune. Just copying the whole query messes with parameters for me.

Fix CoW query

---

cow_amm/daily_rebalancing_4055484.sql

On top of the comparison with the Uniswap reference pool, another interesting reference for CoW AMM performance is the value that a daily rebalancing portfolio (ie a 50:50 ETF that re-allocates once a day) would have over time.
This query achieves this using a recursive SQL statement. It invests 10k on the starting day at the opening price, and then for every consecutive day takes the closing price of the previous day to assess its allocation and perform a rebalancing.
Dune run: https://dune.com/queries/4055484
To cross check, I printed the closing prices for each day and redid the calculation manually for a short time period.

[CoW AMM Performance] 10k growth for daily rebalancing portfolio

---

cowamm/profitability/10k_growth/uni_v2_4047194.sql

The original query was multiplying the initial assessment with the lp_token_price. This is wrong. If we want to compute the lp token amount we can get for 10k, we need to divide.
Similarly, in order to get the current value given the initial amount of lp tokens we need to multiply.

[CoW AMM] Fix uni 10k growth query

---

cowprotocol/accounting/rewards/mainnet/.sqlfluff
cowprotocol/accounting/rewards/mainnet/block_number_interval_from_time_interval_query_3333356.sql
cowprotocol/accounting/rewards/mainnet/full_bonding_pools_query_4056263.sql
cowprotocol/accounting/rewards/mainnet/vouch_registry_query_1541516.sql

This PR migrates queries [3333356](https://dune.com/queries/3333356) and [1541516](https://dune.com/queries/1541516) to the repo. There are also some changes proposed for 1541516, that get rid of the parameter that passes the list of full bonding pools, and proposes instead to use a new query [4056263](https://dune.com/queries/4056263) to hardcode the full bonding pools.

Add block range, bonding pool and vouch queries

---

cowprotocol/accounting/rewards/mainnet/.sqlfluff
cowprotocol/accounting/rewards/mainnet/reduced_bonding_pools_query_4065709.sql
cowprotocol/accounting/rewards/mainnet/service_fee_alternative_query_4066633.sql
cowprotocol/accounting/rewards/mainnet/service_fee_query_4017925.sql

This PR addresses issue #12 and updates the CIP-48 query to use hard-coded values for colocated drivers. 
This change also updates the logic for calculating the 3 month grace period for colocated solvers. Now, the logic only sets the grace period if they are manually marked as being in a reduced bonding pool.
Currently hardcoding all colocated solvers. Updates have been made to the CMS to allow us to get this information in a GitHub action, but since that's not live yet I'm adding these manually.

Update query to use hardcoded values for colocated solvers

---

cowprotocol/accounting/rewards/mainnet/service_fee_query_4017925.sql

This PR addresses a small issue with the hardcoded full bonds in the Service Fee Tracker query (4017925), where the Project Blanc bonding pool was missing. The issue is fixed by pulling the bonds from the dedicated query we have that computes all full bonds.

Use full bonding pools subquery in service fee tracker query

---

cowprotocol/accounting/rewards/mainnet/.sqlfluff
cowprotocol/accounting/rewards/mainnet/unusual_slippage_query_2332678.sql

This PR adds the unusual slippage query to the repo (2332678) and simplifies its code by removing duplications and overlap with the main slippage query.

Add unusual slippage query (2332678)

---

cowprotocol/accounting/rewards/mainnet/.sqlfluff
cowprotocol/accounting/rewards/mainnet/mainnet_dashboard_query_2510345.sql

This PR adds the mainnet payouts dashboard (2510345) to the repo, and simplifies it quite a bit on the way

Add mainnet solver rewards dashboard

---

cowprotocol/accounting/rewards/mainnet/mainnet_dashboard_query_2510345.sql

To make the verification of the payout transaction simpler.
https://dune.com/cowprotocol/cow-solver-rewards?start_time=2024-09-10+00%3A00%3A00&end_time=2024-09-17+00%3A00%3A00

[Easy] Reorder payout dashboard columns

---

cowprotocol/accounting/slippage/raw_slippage_4059683.sql
cowprotocol/accounting/slippage/slippage_4070065.sql

This PR fixes a bug with filtering of slippage per transaction and removes filtering from raw slippage.
Those queries had already been tested on Dune but some small changes had not been copied correctly to the PR.

[EASY] Fix bug with filtering of slippage settlements

---

cowprotocol/accounting/token_imbalances/balance_changes_4021257.sql

This PR changes two things about the balance changes query:
1. MKR burn and mint events on Ethereum Mainnet are now handled correctly.
2. Removes wrong special treatment of sDAI on Gnosis. Those events are always accompanied by all required transfer events. Adding additional transfers resulted in wrong balances. Those additional balance changes are removed now. Examples
It is easier to review the changes by looking at the three commits.
The query was tested by executing on the day range 2024-09-17--2024-09-19 and filtering on the following hashes:
1. [mint](https://etherscan.io/tx/0x92f1fe9f954efec5818c5039a59a5dd54949395149667a29b202e84adb22cfa0), [burn](https://etherscan.io/tx/0xee2f427596714793854d86a21fa2c88e1e38599a16fc58c747ae07e88fe0c78f)
2. …

Update balance changes query

---

cowprotocol/accounting/slippage/slippage_query_3427730.sql

This PR makes the slippage query wrapper consistent with the old slippage query.
- The `blockchain` parameter is set to `ethereum`. With this change, solver rewards does not have to add an additional parameter right now when querying slippage.
- The return type is changed to floating point numbers. This removes the need to have an additional conversion from within solver rewards.
This wrapper will be removed once we have to time to adapt the solver rewards script to the format of the new slippage query (or we remove that query and use a local database).

[EASY] Change slippage wrapper for consistency with old slippage query

---

cowamm/profitability/10k_growth/daily_rebalancing_4055484.sql
cowamm/profitability/10k_growth/hodl_4086902.sql

Not a super meaningful but fun and simple metric to compute, this query plots the 10k growth graph of "not LPing" (ie. holding the two assets). The difference is usually referred to as "impermanent loss".
https://dune.com/queries/4059180/6834667

[CoW AMM] 10k growth for HODL strategy

---

cowprotocol/monitoring/.sqlfluff
cowprotocol/monitoring/solver_approvals_4173928.sql

This PR migrates the old solver approvals query -> https://dune.com/queries/1973291
that is not functioning anymore into a new query that is also slightly improved -> https://dune.com/queries/4173928
The main improvements are:
1.  The query now also checks for approvals not set by solvers by using a placeholder NON-SOLVER string instead of address; in such a case, the name of the responsible address is set to "NON-SOLVER".
2. It works for Gnosis Chain and Arbitrum as well
An improvement that could be done is to pull out the hardcoded proposer accounts from the query and have those as a separate "whitelisted addresses" query, that we can invoke from within the query of this PR.

Add solver approvals query

---

cowamm/profitability/10k_growth/balancer_4106553.sql
cowamm/profitability/invariant_growth/balancer_4106329.sql

This PR adds invariant growth and 10k growth queries for balancer v2 pools similar to how it has been done for Uni v2 pools
Given that Balancer allows for fee discounts from selected partners (e.g. CoW Swap) measuring invariant growth is a bit tricky. I have been relying on the data available in pools_metrics_daily which seems not always populated (thus the data has some gaps).
It also turns out that trusting the Balancer reported $ TVL leads to very skewed graphs. I therefore only use their tables to get the token balances and use price feed we have been using for the other statistics (daily closing according to `price.daily` table) to get a more consistent view.
10k growth looks fine

CoW AMM profitability metrics wrt Balancer v2

---

cowprotocol/accounting/rewards/mainnet/unusual_slippage_query_2332678.sql

This PR fixes a typo in the unusual slippage query.
Due to the type, the link lead to a query with default paramters instead of the parameters from the url.

Fix typo in unusual slippage query

---

cowamm/.sqlfluff
cowamm/cow_amm_cow_with_users_surplus_query_4031724.sql

This PR updates the query for computing CoW surplus of CoW AMMs for the onboing bounty.
The old query was broken due to 80/20-pools since it used a formula for surplus which worked directly with reserves and product invariant ("non-linear surplus"). The resulted in the potential of negative surplus, messing up bounty rewards:
The new query uses surplus as defined in the competition ("linear suplus"). This generalizes to all kinds of CoW AMMs. It also reduces the dependency on a large table which indexes reserves of all CoW AMMs. The results with the updated query ([test query](https://dune.com/queries/4243577?end_time_d83555=2024-11-05+00%3A00%3A00&start_time_d83555=2024-10-29+00%3A00%3A00)) change to this:
One change in behavior is that we now do not reward solvers in cases where the …

Fix CoW AMM CoW surplus query

---

cowprotocol/accounting/price_feed/.sqlfluff
cowprotocol/accounting/price_feed/raw_price_feed_query_4252674.sql

This PR adds a view of the mainnet price feed that we currently upload, that is set up in such a way so that it can be used right away with the existing slippage calculations. This means that for every price feed, and each token, we compute an average price for each hour (as this is what we have also been doing with the Dune price feed).

Add raw price feed query

---

cowamm/cow_amm_cow_with_users_surplus_query_4031724.sql

The current version of the query is removing solvers that do not have their name "registered" on Dune. This PR addresses this by replacing an "Uncatalogued" solver name with the corresponding solver address, so that the solver is still included int he final results
Query has already been updated as it was needed for today's payout.
https://dune.com/queries/4031724?cow_budget_n26d66=28650&start_time_d83555=2024-11-12+00%3A00%3A00&end_time_d83555=2024-11-19+00%3A00%3A00

Update CoW AMM bounty query to handle uncatalogued solvers

---

cowprotocol/accounting/cost_coverage/.sqlfluff
cowprotocol/accounting/cost_coverage/cost_coverage_2601653.sql

This PR adds the weekly "cost coverage" query that we use in the main payouts dashboard on mainnet under version control. It also slightly changes it so that it can account for the daily fee withdrawals at 00:00 UTC that we recently introduced.
Here is the current version of the query:
https://dune.com/queries/2601653
Line 11 is the only line that is changed with this PR

Add protocol cost coverage query

---

cowprotocol/solver_dashboard/cost_coverage_by_solver_environment_1372854.sql

This PR fixes a small typo that is breaking one query

[Trivial] Fix typo

---

.github/nitpicks.yml
.github/workflows/pull-request.yaml
cowamm/kpi/competitors/curve/curve_largest_2token_pools_4232976.sql
cowamm/kpi/competitors/uni_swap_style/largest_uni_style_kpis_4304295.sql
cowamm/kpi/competitors/uni_swap_style/largest_uni_style_pools_4303563.sql
cowamm/kpi/tvl_by_chain_4096107.sql
cowamm/profitability/10k_growth/balancer_4106553.sql
cowamm/profitability/10k_growth/cow_4047078.sql
cowamm/profitability/10k_growth/daily_rebalancing_4055484.sql
cowamm/profitability/10k_growth/hodl_4086902.sql
cowamm/profitability/10k_growth/uni_v2_4047194.sql
cowamm/profitability/invariant_growth/balancer_4106329.sql
cowamm/profitability/invariant_growth/uni_v2_4060136.sql
cowamm/tvl_by_tx_4059700.sql
cowprotocol/accounting/cost_coverage/cost_coverage_2601653.sql
cowprotocol/accounting/price_feed/raw_price_feed_query_4252674.sql
cowprotocol/accounting/rewards/mainnet/mainnet_dashboard_query_2510345.sql
cowprotocol/accounting/slippage/slippage_prices_4064601.sql
cowprotocol/solver_dashboard/cost_coverage_by_solver_environment_1372854.sql
cowprotocol/solver_dashboard/cost_coverage_production_solver_1372758.sql
cowprotocol/solver_dashboard/cow_rewards_totals_1372979.sql
cowprotocol/solver_dashboard/deprecated_queries/solver_rewards_totals_1821285.sql
cowprotocol/solver_dashboard/internal_monitoring/solver_quote_rewards_3641173.sql

Since `prices.usd` is deprecated (https://docs.dune.com/data-catalog/curated/prices/overview).
Also add nitpicker that will comment whenever a new query is checked in with the legacy table.

Change prices.usd to prices.minute

---

cowprotocol/accounting/rewards/mainnet/excluded_batches_query_3490353.sql

This PR copies the query from Dune into the repo.
The query on Dune has been changed a few times. But those changes had not moved to this repo yet.

Mirror changes from dune to excluded batches

---

cowprotocol/execution_quality/.sqlfluff
cowprotocol/execution_quality/.sqlflull
cowprotocol/execution_quality/aggregator_markout_4334277.sql
cowprotocol/execution_quality/comparison_4334259.sql

This query is based off of @PoloX2021 query to compare our execution quality with Paraswap on Aave tokens (cf. https://dune.com/queries/4274948?number_tokens_t6c1ea=100) but allowing to chose arbitrary aggregators/chains to compare with.
The basic idea is to compute "t0 markout" of trades with the Dune price table for both competitors and then volume weight the ratio of those markouts to get a total edge.
I noticed an issue in the original query that was simply computing `sum(volume * improvement) / sum(volume)` that it overcounts "positive improvements" and thus doesn't lead to symmetric results (ie. you may find when comparing Paraswap to CoW that Paraswap is better, and when comparing CoW to Paraswap that CoW is better).
This is addressed by using a geometric volume weighted average …

Execution quality comparison

---

cowamm/kpi/tvl_by_chain_4096107.sql
cowamm/profitability/10k_growth/balancer_4106553.sql
cowamm/profitability/10k_growth/cow_4047078.sql
cowamm/profitability/10k_growth/daily_rebalancing_4055484.sql
cowamm/profitability/10k_growth/hodl_4086902.sql
cowamm/profitability/10k_growth/uni_v2_4047194.sql
cowamm/profitability/invariant_growth/balancer_4106329.sql

#76 changed the use of the price query. However, `prices_daily` no longer has a `price_close` column breaking a bunch of queries.
This PR fixes this by changing the column to the appropriate `price` column.

[Easy] Fix usage of daily prices

---

cowprotocol/accounting/rewards/mainnet/partner_fees_query_3602560.sql

`dataset_app_data_mainnet` will no longer be populated (new tables are `dataset_app_data_mainnet_prod` and `dataset_app_data_mainnet_barn`).
The new tables can be accessed via the materialised view [`result_cow_protocol_ethereum_app_data`](https://dune.com/queries/3921295)

Use consolidated app data view

---

cowamm/.sqlfluff
cowamm/kpi/competitors/curve/curve_kpis_4232873.sql
cowamm/kpi/competitors/curve/curve_largest_2token_pools_4232976.sql
cowamm/kpi/competitors/uni_swap_style/largest_uni_style_kpis_4304295.sql
cowamm/kpi/competitors/uni_swap_style/largest_uni_style_pools_4303563.sql

Updated the queries to fit the new table prices.minute to use them more efficiently. 
For total TVL, switched to the table prices.day: less expensive and gets an average over the time frame for the study

Optimizing competitor kpis

---

cowprotocol/accounting/rewards/mainnet/partner_fees_query_3602560.sql

This PR updates the partner fee query to use the new raw_order_data table, and also it parameterizes it by blockchain. Change has already been applied:
https://dune.com/queries/3602560?end_time_d83555=2024-12-10+00%3A00%3A00

Update partner fee query

---

cowprotocol/accounting/fees/protocol_fees_by_order_class_3703312.sql

Follow-up PR to #97 , that fixes a small issue and also extends the query to all chains.

Extend protocol fees per order class query to all chains

---

cowprotocol/accounting/rewards/mainnet/unusual_slippage_query_2332678.sql

This PR updates the outdated version of the query that was in this repo (the phalcon explorer view link was missing) and also extends it to work for all chains.
Changes have already been applied and can be tested here:
https://dune.com/queries/2332678?start_time_d83555=2024-12-10+00%3A00%3A00&end_time_d83555=2024-12-17+00%3A00%3A00

Update and extend unusual slippage query to all chains

---

cowprotocol/accounting/token_imbalances/balance_changes_4021257.sql

This PR extends query 4021257 for WETH withdrawals and deposits on Base.

Add Base WETH withdrawal and deposit events tracking for Balance Changes query

---

cowprotocol/accounting/fees/protocol_fees_by_order_class_3703312.sql

The protocol fee per order class query had a small bug, that this PR fixes. Change has already been applied.
https://dune.com/queries/3703312?end_time_d83555=2024-12-24+00%3A00%3A00&start_time_d83555=2024-12-17+00%3A00%3A00

Protocol fee per order class query bug fix

---

cowprotocol/accounting/rewards/unusual_slippage_query_2332678.sql
cowprotocol/accounting/slippage/slippage_4070065.sql

This PR adds additional columns to the slippage and unusual slippage query. They are meant to simplify validation and debugging of payments.
- `imbalance_usd`: The total imbalance of the transaction. It is the aggregated dollar value of all raw imbalances in the different tokens.
- `protocol_fee_usd`: The total protocol fee collected in a transaction.
- `network_fee_usd`: The total network fee as recovered from the discrepancy of uniform clearing prices and effective exchange rate of trades, corrected using protocol fees.
The total slippage of a settlement then satisfies `slippage_usd = imbalance_usd - protocol_fee - network_fee`.
The queries can be tested on dune for [slippage](https://dune.com/queries/4527447?end_time_d83555=2025-01-06+00%3A00%3A00&start_time_d83555=2024-12-31+00%3A00%3A …

Add fee columns to (unusual) slippage query

---

cowprotocol/accounting/slippage/slippage_prices_4064601.sql

This PR adds the WETH Base address to the slippage prices query. Change has been already applied:
https://dune.com/queries/4064601

Add Base WETH to slippage prices

---

.sqlfluff
cowprotocol/revenue/monthly_dao_revenue_3700123.sql
cowprotocol/revenue/total_dao_revenue_3690521.sql

One of our most important [dashboards](https://dune.com/cowprotocol/cow-revenue) isn't yet under version control. In the next few PRs I'm going to add the existing queries (corrected for the new order rewards table) and unify the dashboard to show the same statistics per chain.
This PR adds the monthly total per fee area (not yet multi-chain), which now also powers the total protocol fee query (which became a trivial `select sum(...)`

[Revenue] Add monthly DAO revenue query

---

.sqlfluff
cowprotocol/revenue/.sqlfluff
cowprotocol/revenue/daily_revenue_by_integration_per_chain_4515022.sql
cowprotocol/revenue/daily_revenue_by_solver_per_chain_4515000.sql
cowprotocol/revenue/daily_revenue_per_chain_4514883.sql
cowprotocol/revenue/monthly_dao_revenue_3700123.sql
cowprotocol/revenue/total_dao_revenue_3690521.sql
cowprotocol/revenue/totals_per_chain_4514952.sql
cowprotocol/revenue/trade_revenue_per_chain_4217030.sql

This PR adds two more useful queries which compute the fee captured by solver (1) and by integration (2) for a given target chain.
These graphs can now be seen in https://dune.com/cowprotocol/cow-revenue for each chain.

[Revenue] Add Revenue by solver/integrator per chain

---

cowamm/tvl_by_tx_4059700.sql

Prices.minute is doubling the output of lines. Distinct removes this issue

Issues with the prices.minute table

---

cowprotocol/accounting/cost_coverage/.sqlfluff
cowprotocol/accounting/cost_coverage/cost_coverage_2601653.sql

This PR updates the cost coverage query that shows up in the main payouts dashboard. 
Query has been updated and can be tested here: https://dune.com/queries/2601653?start_time_d83555=2024-12-31+00%3A00%3A00&end_time_d83555=2025-01-07+00%3A00%3A00
~I still want to do some sanity checks about what exactly we are computing at the very end; in case you have any comments/feedback, let me know~

Extend cost coverage query to all networks

---

cowprotocol/accounting/rewards/main_rewards_dashboard_query_2510345.sql

This PR fixes a delicate issue in the main rewards query, that has to do with the block range that determines which auctions/orders to include in the accounting.
Note that the solver rewards script uses the correct convention, while the dune query might skip at most one auction in each accounting period due to an interval being open instead of closed.
See the following relevant references in the solver rewards repo:
- https://github.com/cowprotocol/solver-rewards/blob/a3213a8ecd08bd267591f19fe4510a67b78521dc/queries/orderbook/prod_batch_rewards.sql#L14
- https://github.com/cowprotocol/solver-rewards/blob/a3213a8ecd08bd267591f19fe4510a67b78521dc/queries/orderbook/order_data.sql#L25
- https://github.com/cowprotocol/solver-rewards/blob/a3213a8ecd08bd267591f19fe4510a67b78521dc/queries/orderboo …

Fix open interval issue in rewards query

---

cowamm/tvl_by_tx_4059700.sql

The prices.minute table is completely messed up currently. 
This PR switch to prices.day. This table is less precise because we are looking at individual transactions. But it does not impact daily performance metrics.

Change prices from minute to day to avoid issues in the db

---

cowamm/cow_amm_cow_with_users_surplus_query_4031724.sql

This PR add support for Base network to the CoW AMM bounty on CoW surplus.
Since all queries used within already work on base, only one additional table needed to be added to this query.
The modified query can be tested [here](https://dune.com/queries/4632908?end_time_d83555=2025-01-28+00%3A00%3A00).
This has not been rigorously tested. The results seem reasonable. Overall, there do not seem to be any significant CoWs on Base.

Add Base network to cow amm surplus query

---

cowprotocol/accounting/token_imbalances/balance_changes_4021257.sql

This PR changes how duplicates are handled in balance changes. The new query can be tested [here](https://dune.com/queries/4636979?end_time_d83555=2025-01-28+00%3A00%3A00&start_time_d83555=2025-01-21+00%3A00%3A00).
Before, with a `union distinct` all duplicate rows were removed. This led to wrongfully removing balance changes in auctions where there are multiple withdrawals of the same amount (e.g. [here](https://etherscan.io/tx/0x08afb56d779bc2034bfcc78a1d470cc82c8c55c4394fda3875d426de869f8ca2) and [here](https://etherscan.io/tx/0x74e730407d3061e60527629123c1e7b43e3e73b4ba4232bd077c7109ac5e8325)). Using `union all` removes this problem.
Comparing the new and old query for the accounting week 2025-01-21 to 2025-01-28, there are just 6 additional rows which can be traced to two settlements …

Fix bug with removed duplicates in balance changes

---

cowamm/kpi/competitors/uni_swap_style/largest_uni_style_pools_4303563.sql

Use a base query to reference all the Uniswap pools. 
Easier to store all the parameters in the same place.
Test query [here](https://dune.com/queries/4634430).

[Easy] All Uniswap pools

---

cowamm/kpi/competitors/cow_amm/tvl_all_cow_amms_4340356.sql
cowamm/kpi/competitors/curve/curve_kpis_4232873.sql
cowamm/kpi/competitors/uni_swap_style/largest_uni_style_kpis_4304295.sql

Improving the speed of some queries and reverting to the prices.usd table for accurate information.
This means we won't be supporting new tokens, but it's better than having false data for all tokens.

Fix performance kpi competitors

---

mevblocker/fees/payment_due_4005800.sql
mevblocker/fees/value_per_tx_4188777.sql

MEVBlocker fee is increasing to 30% as of February. In order to not disrupt the billing transaction tomorrow (which should still charge 20% fee for the previous week), this PR also adjusts the "payment due " query downward to account for the old fee.
However, the per block fee that will be announced in the billing transaction and is valid for the following week already uses the 30% fee tier.
Towards the end of the week we then need to revert the change to payment due query to make sure next week the 30% fee is applied.

[MEVBlocker] Prepare fee bump

---

mevblocker/fees/value_per_tx_4188777.sql

For some upstream partner dashboards, Alex needs to have access to the "from" address of the user transaction as well as to the refund recipient.

[MEVBlocker] additional columns on base value_per_tx query

---

mevblocker/fees/payment_due_4005800.sql
mevblocker/fees/value_per_tx_4188777.sql

Increase fees from 30% to 40%. At the same time keep payments due at 30% fee.
Price reduction to be reverted after next payment (5 Mar 2025).

[MEV Blocker] Prepare Fee Bump

---

cowprotocol/competitor_analysis/.sqlfluff
cowprotocol/competitor_analysis/cow_alternatives_analysis_4810844.sql
cowprotocol/competitor_analysis/cow_vs_competition_4807448.sql

Added competitor analysis queries to the dune queries repo

Competitor analysis

---

cowprotocol/accounting/rewards/partner_fees_query_3602560.sql

Requested here:
https://cowservices.slack.com/archives/C036JAGRQ04/p1740041967079139
Change has already been applied here.
https://dune.com/queries/3602560

Differentiate between different Safe fees

---

cowprotocol/accounting/slippage/slippage_prices_4064601.sql

This PR hardcodes the price of `0x22af33fe49fd1fa80c7149773dde5890d3c76f3b` for the week of March 4-11, 2025, as it is currently completely off.
To see this, you can use the current version of the query, and check the price of that token by setting, for example, start time being March 8 and end time being March 10; https://dune.com/queries/4064601?start_time_d83555=2025-03-08+00%3A00%3A00&end_time_d83555=2025-03-10+00%3A00%3A00&blockchain_t6c1ea=base.
The updated query can be found here:
https://dune.com/queries/4836344

Fix BNKR price on Base for week of March 4-11, 2025

---

cowprotocol/accounting/rewards/main_rewards_dashboard_query_2510345.sql

This PR removes the scaling with the service fee that was accidentally done when rewards are negative, and aligns the Dune's dahsboard behavior with what the solver rewards script computes.

Remove service fee scaling for negative rewards

---

cowprotocol/accounting/rewards/unusual_slippage_query_2332678.sql

Small change in the url, so link in query needs to be updated

Update phalcon explorer url in unusual slippage query

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

Garbage token that was denylisted, where owners could transfer out from the settlement contract (see [here](https://etherscan.io/tx/0x6259db0f1bac7ecc9b69cb35ea3b6432c799ce6031c85abefa62518ba22e530f))

Exclude tx with scam token

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

Proper indexing of flashloans queries is not yet completed on Dune, so the [test tx](https://etherscan.io/tx/0x683fff5607fac2fd249050794fedd47875e3f94762ee885c7514b080787989c5) on mainnet barn that was executed last week currently creates issues with the payouts script. Because of that, we decided to exclude it from slippage accounting. It is easy to see that slippage in the tx is essentially zero.
Change has been already applied.

Exclude barn flashloans tx from slippage

---

cowprotocol/solver_dashboard/ranked_active_solvers_1756858.sql

This PR fixes a data integrity issue in the `V2: Ranked Active Solvers` Dune query, where solver metrics were **inflated due to row duplication** caused by directly joining `batches` with `trades` using `tx_hash`.
- The original query included:
```sql
INNER JOIN trades t ON b.tx_hash = t.tx_hash
```
Since many batches have multiple trades, this caused row multiplication, leading to overcounting.
- Added a trade_agg CTE to aggregate trade metrics per tx_hash.
- Joined batches to this pre-aggregated view to avoid row duplication.
- Ensured only settled batches (those with at least one trade) are included by joining against trade_agg.
- Preserved solver-level filters (environment NOT IN ('test', 'service'), active = TRUE).

Prevent Duplicate Counting in Solver Metrics by Pre-Aggregating Trades

---

cowprotocol/ethflow/.sqlfluff
cowprotocol/ethflow/missing_refunds_4904398.sql

Adds an optional variable, which we can configure in infra to exclude certain app codes from this alert. This is useful for integrations which are knowingly broken (e.g. infinex, even after trying to reach out multiple times) and which are causing unactionable alerts in our production channel.
[Query](https://dune.com/queries/4904398?grace_period=10&network=base&start_time=2025-05-21+16%3A00%3A08.602970&end_time=2025-05-21+17%3A00%3A08.602970&category=third_party_data&catalog=dune&schema=cowprotocol&id=dune.cowprotocol.result_cow_protocol_ethereum_app_data&end_time_d83555=2025-05-21+17%3A00%3A08.602970&grace_period_n26d66=10&network_e15077=base&start_time_d83555=2025-05-21+16%3A00%3A08.602970&ignored_app_codes_t6c1ea=%27OneKey+CowSwap%27) ignoring an otherwise non refunded partner.

[ETH Flow Missing Refund] Add variable to ignore certain app codes

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

Some invalid prices on Dune have lead to wrong slippage amounts for the RIO token. This PR excludes these transactions.
You can check the prices with this query on Dune:
```
select * from prices.usd where (
blockchain = 'ethereum' and minute = TIMESTAMP '2025-05-22 16:19' and contract_address = 0xf21661d0d1d76d3ecb8e1b9f1c923dbfffae4097
) or (
blockchain = 'ethereum' and minute = TIMESTAMP '2025-05-22 16:17' and contract_address = 0xf21661d0d1d76d3ecb8e1b9f1c923dbfffae4097
);
```
The RIO token shows a price of `0.344343` USD while the auction has a price of `0.2` USD.

Exclude slippage transactions May 2025

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

This PR removes this tx
https://etherscan.io/tx/0x939879ff06f5c9e94d3e27f3b78cbcbb8eae72782a5fdcac831c743e2a5492e1
from slippage accounting as Dune has a wrong price for the sell token (and the solver trades the fee so as to collect it in the buy token, thus messing up with the accounting).
One can run this query
```
select * from cow_protocol_ethereum.trades
where sell_token_address = 0xC91a71A1fFA3d8B22ba615BA1B9c01b2BBBf55ad or buy_token_address = 0xC91a71A1fFA3d8B22ba615BA1B9c01b2BBBf55ad
```
to verify that no other transaction involving this token took place during this accounting period.
Attaching a picture that shows the wrong price

Exclude tx from slippage for June 17-24, 2025

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

This PR updates the excluded_batches_query to exclude this tx from the slippage:
https://app.blocksec.com/explorer/tx/eth/0xC60E65F001E2CEDE1A2399FBF40E049B7F7BD57D8A982DE66EF4E44C23967589
This is listed on Dune as having a slippage of -8172 usd.

Exclude tx from slippage

---

cowprotocol/accounting/rewards/main_rewards_dashboard_query_2510345.sql

This PR fixes a small bug introduced in the main rewards query where some parameters were not passed when invoking the auction data query.
Fix has already been applied in the query: https://dune.com/queries/2510345

Fix bug in rewards query

---

cowprotocol/accounting/rewards/auction_data_5270914.sql

While filtering on transactions, we should try to involve block_date whenever we can. This is because the transactions (logs,traces) tables are partitioned on block_date and it helps avoid looking into the full table if we add it in the filter

added blocks data to use partitioning in tx

---

cowprotocol/accounting/rewards/auction_data_5270914.sql

As the auction data query (https://dune.com/queries/5270914) is still slow, an easy win, i believe, is to use the cow_protocol_{{blockchain}}.batches table that is already indexed by Dune instead of the much larger {{blockchain}}.transactions table that is currently being used.
New query: https://dune.com/queries/5543963
Test query: https://dune.com/queries/5544060

Improve auction data query

---

cowprotocol/accounting/rewards/main_rewards_dashboard_query_2510345.sql

In an attempt to finally get the main solver rewards dashboard to work again (which i thought i had with PR #221 but it seems it doesn't work), i propose to remove the subquery that is meant to exclude certain auction ids from rewards.
This was only used once when the issue with buy order surplus showed up. If it shows up again, we can always add it back, but for now it doesn't serve anything and only slows down the query.

Remove the exclude auctions from rewards subquery from main rewards query

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

This PR excludes this tx
https://etherscan.io/tx/0x5c550c99a39a7315a699d6e5c6592038f26f7d93b787cf63312e38a72df17e2a
that shows a negative slippage of $842.
https://dune.com/queries/4059683?raw_slippage_table_name_e15077=raw_slippage_per_transaction&end_time_d83555=2025-09-02+00%3A00%3A00&start_time_d83555=2025-08-26+00%3A00%3A00

Exclude mainnet tx from slippage accounting for week of August 29 - Sep 2, 2025

---

cowprotocol/accounting/slippage/slippage_prices_4064601.sql

It was flagged that these 2 txs don't show any slippage on Dune, due to missing prices.
https://etherscan.io/tx/0x9cab916a0766d8a2b3f235f29766923d51b50a58f44ef5c4d6a2cbeba669e600
https://etherscan.io/tx/0x31a5fa7e29c644563ef583d641d851b1689780882c107b4799b5a4a1fb0f3a35
One can verify this by looking at this query:
https://dune.com/queries/4059683?end_time_d83555=2025-09-02+00%3A00%3A00&raw_slippage_table_name_e15077=raw_slippage_per_transaction&start_time_d83555=2025-08-26+00%3A00%3A00
and filtering by tx hash
The reason for this is due to missing prices of the buy tokens in the relevant hour time window when each tx took place, which can be verified here:
https://dune.com/queries/4064601?blockchain_t6c1ea=ethereum&end_time_d83555=2025-09-02+00:00:00&start_time_d83555=2025-08-26+00:00:00 …

Add prices to mainnet price feed for August 29 - Sep2, 2025 accounting

---

cowprotocol/accounting/rewards/partner_fees_query_3602560.sql

The `0x63695eee2c3141bde314c5a6f89b98e62808d716` address is deprecated and we want to redirect the fees to `0xe344241493d573428076c022835856a221db3e26`. This PR implements that

Fix partner fees query for partner recipient

---

cowprotocol/accounting/slippage/slippage_prices_4064601.sql

As the `prices.usd` Dune table is not working great with Aave tokens, this query uses a mapping of these tokens to the underlying asset in order to use the address of the underlying asset for recovering the price of the token itself.
The mapping is done using this cte
```
aave_tokens_mapping as (
select distinct
chain as blockchain,
atoken as atoken_address,
asset as underlying_address
from aave_v3_multichain.poolconfigurator_evt_reserveinitialized
union distinct
select distinct
'ethereum' as blockchain,
atoken as atoken_address,
asset as underlying_address
from aave_v3_lido_ethereum.poolconfigurator_evt_reserveinitialized
union distinct
select distinct
'ethereum' as blockchain,
atoken as atoken_address,
asset as underlying_address
from …
```

Adapt price feed in slippage accounting for Aave tokens

---

cowprotocol/accounting/rewards/excluded_batches_query_3490353.sql

This PR excludes 3 txs from slippage on mainnet. They all include the same token that does some additional transfers from the Vault Relayer to the settlement that is perceived as slippage
https://etherscan.io/tx/0x149c90ed4aa005a8aefc4b8bb85bfeaf31f35151989953a7cac3187ae8e9cb2d
https://etherscan.io/tx/0xc3e9ab2accbc9ba20868a55df63374b81edc8d3e92b9528d61085792267f744b
https://etherscan.io/tx/0xf15e37449c1492b18088e42608a281430a8ad45feba5a7763c8e587582ac1dd9

Exclude txs from slippage for Sep9-16, 2025

---

cowprotocol/accounting/slippage/slippage_prices_4064601.sql

This tx currently doesn't show up in the slippage accounting
https://basescan.org/tx/0xcd7e4084e5c06553637159745c66fd70e1123faa46d9cd6f00de3611635c8ec2
because the price of 0x2e285de4c868d225949dbdaf82cd5e28497c52bf is missing.
This PR adds an approximate price for this

Add price for Base tx
